---
# tasks file for artifactory
- debug: msg="Starting role artifactory v1.0.1"

- name: remove artifactory stack
  shell: "docker stack rm {{artifactory_stack_name}}"
  when: artifactory_remove

- name: make sure mount paths exist
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ artifactory_datapath }}"
    - "{{ artifactory_datapath }}/artifactory"
    - "{{ artifactory_datapath }}/nginx"
    - "{{ artifactory_datapath }}/nginx/logs"
    - "{{ artifactory_postgres_datapath | dirname }}"
    - "{{ artifactory_postgres_datapath }}"

- name: Drop NGINX config file
  copy:
    dest: "{{ artifactory_datapath }}/nginx/nginx.conf"
    content: "{{ artifactory_proxy_config }}"
    mode: 0644

- name: write template to temp location
  template:
    src: templates/docker-compose.yml.j2
    dest: "/tmp/{{artifactory_stack_name}}-docker-compose.yml"
  when: not artifactory_remove

- name: run docker stack
  shell: "docker stack deploy -c /tmp/{{artifactory_stack_name}}-docker-compose.yml {{artifactory_stack_name}}" 
  when: not artifactory_remove

- debug: msg="WARNING! The docker stack command does not return an error if the stack doesn't launch properly."
